//
//  CompositionModel.swift
//  NeuralObscura
//
//  Created by Paul Bergeron on 9/20/16.
//  Copyright © 2016 Paul Bergeron. All rights reserved.
//

import Foundation

class CompositionModel {
    var layerData = [String: StyleModelData]()

    init() {
        // PASTE INIT DATA HERE
        layerData["r4_c2_W"] = StyleModelData(modelName: "composition", rawFileName: "r4_c2_W")
        //r4_c2_W shape = (128, 128, 3, 3)
        layerData["r4_c2_b"] = StyleModelData(modelName: "composition", rawFileName: "r4_c2_b")
        //r4_c2_b shape = (128,)
        layerData["r4_c1_W"] = StyleModelData(modelName: "composition", rawFileName: "r4_c1_W")
        //r4_c1_W shape = (128, 128, 3, 3)
        layerData["r4_c1_b"] = StyleModelData(modelName: "composition", rawFileName: "r4_c1_b")
        //r4_c1_b shape = (128,)
        layerData["r4_b1_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r4_b1_gamma")
        //r4_b1_gamma shape = (128,)
        layerData["r4_b1_beta"] = StyleModelData(modelName: "composition", rawFileName: "r4_b1_beta")
        //r4_b1_beta shape = (128,)
        layerData["r4_b2_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r4_b2_gamma")
        //r4_b2_gamma shape = (128,)
        layerData["r4_b2_beta"] = StyleModelData(modelName: "composition", rawFileName: "r4_b2_beta")
        //r4_b2_beta shape = (128,)
        layerData["r5_c2_W"] = StyleModelData(modelName: "composition", rawFileName: "r5_c2_W")
        //r5_c2_W shape = (128, 128, 3, 3)
        layerData["r5_c2_b"] = StyleModelData(modelName: "composition", rawFileName: "r5_c2_b")
        //r5_c2_b shape = (128,)
        layerData["r5_c1_W"] = StyleModelData(modelName: "composition", rawFileName: "r5_c1_W")
        //r5_c1_W shape = (128, 128, 3, 3)
        layerData["r5_c1_b"] = StyleModelData(modelName: "composition", rawFileName: "r5_c1_b")
        //r5_c1_b shape = (128,)
        layerData["r5_b1_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r5_b1_gamma")
        //r5_b1_gamma shape = (128,)
        layerData["r5_b1_beta"] = StyleModelData(modelName: "composition", rawFileName: "r5_b1_beta")
        //r5_b1_beta shape = (128,)
        layerData["r5_b2_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r5_b2_gamma")
        //r5_b2_gamma shape = (128,)
        layerData["r5_b2_beta"] = StyleModelData(modelName: "composition", rawFileName: "r5_b2_beta")
        //r5_b2_beta shape = (128,)
        layerData["r1_c2_W"] = StyleModelData(modelName: "composition", rawFileName: "r1_c2_W")
        //r1_c2_W shape = (128, 128, 3, 3)
        layerData["r1_c2_b"] = StyleModelData(modelName: "composition", rawFileName: "r1_c2_b")
        //r1_c2_b shape = (128,)
        layerData["r1_c1_W"] = StyleModelData(modelName: "composition", rawFileName: "r1_c1_W")
        //r1_c1_W shape = (128, 128, 3, 3)
        layerData["r1_c1_b"] = StyleModelData(modelName: "composition", rawFileName: "r1_c1_b")
        //r1_c1_b shape = (128,)
        layerData["r1_b1_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r1_b1_gamma")
        //r1_b1_gamma shape = (128,)
        layerData["r1_b1_beta"] = StyleModelData(modelName: "composition", rawFileName: "r1_b1_beta")
        //r1_b1_beta shape = (128,)
        layerData["r1_b2_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r1_b2_gamma")
        //r1_b2_gamma shape = (128,)
        layerData["r1_b2_beta"] = StyleModelData(modelName: "composition", rawFileName: "r1_b2_beta")
        //r1_b2_beta shape = (128,)
        layerData["r2_c2_W"] = StyleModelData(modelName: "composition", rawFileName: "r2_c2_W")
        //r2_c2_W shape = (128, 128, 3, 3)
        layerData["r2_c2_b"] = StyleModelData(modelName: "composition", rawFileName: "r2_c2_b")
        //r2_c2_b shape = (128,)
        layerData["r2_c1_W"] = StyleModelData(modelName: "composition", rawFileName: "r2_c1_W")
        //r2_c1_W shape = (128, 128, 3, 3)
        layerData["r2_c1_b"] = StyleModelData(modelName: "composition", rawFileName: "r2_c1_b")
        //r2_c1_b shape = (128,)
        layerData["r2_b1_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r2_b1_gamma")
        //r2_b1_gamma shape = (128,)
        layerData["r2_b1_beta"] = StyleModelData(modelName: "composition", rawFileName: "r2_b1_beta")
        //r2_b1_beta shape = (128,)
        layerData["r2_b2_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r2_b2_gamma")
        //r2_b2_gamma shape = (128,)
        layerData["r2_b2_beta"] = StyleModelData(modelName: "composition", rawFileName: "r2_b2_beta")
        //r2_b2_beta shape = (128,)
        layerData["r3_c2_W"] = StyleModelData(modelName: "composition", rawFileName: "r3_c2_W")
        //r3_c2_W shape = (128, 128, 3, 3)
        layerData["r3_c2_b"] = StyleModelData(modelName: "composition", rawFileName: "r3_c2_b")
        //r3_c2_b shape = (128,)
        layerData["r3_c1_W"] = StyleModelData(modelName: "composition", rawFileName: "r3_c1_W")
        //r3_c1_W shape = (128, 128, 3, 3)
        layerData["r3_c1_b"] = StyleModelData(modelName: "composition", rawFileName: "r3_c1_b")
        //r3_c1_b shape = (128,)
        layerData["r3_b1_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r3_b1_gamma")
        //r3_b1_gamma shape = (128,)
        layerData["r3_b1_beta"] = StyleModelData(modelName: "composition", rawFileName: "r3_b1_beta")
        //r3_b1_beta shape = (128,)
        layerData["r3_b2_gamma"] = StyleModelData(modelName: "composition", rawFileName: "r3_b2_gamma")
        //r3_b2_gamma shape = (128,)
        layerData["r3_b2_beta"] = StyleModelData(modelName: "composition", rawFileName: "r3_b2_beta")
        //r3_b2_beta shape = (128,)
        layerData["b4_gamma"] = StyleModelData(modelName: "composition", rawFileName: "b4_gamma")
        //b4_gamma shape = (64,)
        layerData["b4_beta"] = StyleModelData(modelName: "composition", rawFileName: "b4_beta")
        //b4_beta shape = (64,)
        layerData["b5_gamma"] = StyleModelData(modelName: "composition", rawFileName: "b5_gamma")
        //b5_gamma shape = (32,)
        layerData["b5_beta"] = StyleModelData(modelName: "composition", rawFileName: "b5_beta")
        //b5_beta shape = (32,)
        layerData["b1_gamma"] = StyleModelData(modelName: "composition", rawFileName: "b1_gamma")
        //b1_gamma shape = (32,)
        layerData["b1_beta"] = StyleModelData(modelName: "composition", rawFileName: "b1_beta")
        //b1_beta shape = (32,)
        layerData["b2_gamma"] = StyleModelData(modelName: "composition", rawFileName: "b2_gamma")
        //b2_gamma shape = (64,)
        layerData["b2_beta"] = StyleModelData(modelName: "composition", rawFileName: "b2_beta")
        //b2_beta shape = (64,)
        layerData["b3_gamma"] = StyleModelData(modelName: "composition", rawFileName: "b3_gamma")
        //b3_gamma shape = (128,)
        layerData["b3_beta"] = StyleModelData(modelName: "composition", rawFileName: "b3_beta")
        //b3_beta shape = (128,)
        layerData["c3_W"] = StyleModelData(modelName: "composition", rawFileName: "c3_W")
        //c3_W shape = (128, 64, 4, 4)
        layerData["c3_b"] = StyleModelData(modelName: "composition", rawFileName: "c3_b")
        //c3_b shape = (128,)
        layerData["c2_W"] = StyleModelData(modelName: "composition", rawFileName: "c2_W")
        //c2_W shape = (64, 32, 4, 4)
        layerData["c2_b"] = StyleModelData(modelName: "composition", rawFileName: "c2_b")
        //c2_b shape = (64,)
        layerData["c1_W"] = StyleModelData(modelName: "composition", rawFileName: "c1_W")
        //c1_W shape = (32, 3, 9, 9)
        layerData["c1_b"] = StyleModelData(modelName: "composition", rawFileName: "c1_b")
        //c1_b shape = (32,)
        layerData["d2_W"] = StyleModelData(modelName: "composition", rawFileName: "d2_W")
        //d2_W shape = (64, 32, 4, 4)
        layerData["d2_b"] = StyleModelData(modelName: "composition", rawFileName: "d2_b")
        //d2_b shape = (32,)
        layerData["d3_W"] = StyleModelData(modelName: "composition", rawFileName: "d3_W")
        //d3_W shape = (32, 3, 9, 9)
        layerData["d3_b"] = StyleModelData(modelName: "composition", rawFileName: "d3_b")
        //d3_b shape = (3,)
        layerData["d1_W"] = StyleModelData(modelName: "composition", rawFileName: "d1_W")
        //d1_W shape = (128, 64, 4, 4)
        layerData["d1_b"] = StyleModelData(modelName: "composition", rawFileName: "d1_b")
        //d1_b shape = (64,)
    }
}
