//
//  CompositionModel.swift
//  NeuralObscura
//
//  Created by Paul Bergeron on 9/20/16.
//  Copyright © 2016 Paul Bergeron. All rights reserved.
//

import Foundation

class CompositionModel {
    var layerData = [String: StyleModelData]()

    init() {
        layerData["composition_r4_c2_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r4_c2_W")
        //composition_r4_c2_W shape = (128, 128, 3, 3)
        layerData["composition_r4_c2_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r4_c2_b")
        //composition_r4_c2_b shape = (128,)
        layerData["composition_r4_c1_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r4_c1_W")
        //composition_r4_c1_W shape = (128, 128, 3, 3)
        layerData["composition_r4_c1_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r4_c1_b")
        //composition_r4_c1_b shape = (128,)
        layerData["composition_r4_b1_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r4_b1_gamma")
        //composition_r4_b1_gamma shape = (128,)
        layerData["composition_r4_b1_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r4_b1_beta")
        //composition_r4_b1_beta shape = (128,)
        layerData["composition_r4_b2_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r4_b2_gamma")
        //composition_r4_b2_gamma shape = (128,)
        layerData["composition_r4_b2_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r4_b2_beta")
        //composition_r4_b2_beta shape = (128,)
        layerData["composition_r5_c2_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r5_c2_W")
        //composition_r5_c2_W shape = (128, 128, 3, 3)
        layerData["composition_r5_c2_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r5_c2_b")
        //composition_r5_c2_b shape = (128,)
        layerData["composition_r5_c1_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r5_c1_W")
        //composition_r5_c1_W shape = (128, 128, 3, 3)
        layerData["composition_r5_c1_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r5_c1_b")
        //composition_r5_c1_b shape = (128,)
        layerData["composition_r5_b1_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r5_b1_gamma")
        //composition_r5_b1_gamma shape = (128,)
        layerData["composition_r5_b1_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r5_b1_beta")
        //composition_r5_b1_beta shape = (128,)
        layerData["composition_r5_b2_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r5_b2_gamma")
        //composition_r5_b2_gamma shape = (128,)
        layerData["composition_r5_b2_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r5_b2_beta")
        //composition_r5_b2_beta shape = (128,)
        layerData["composition_r1_c2_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r1_c2_W")
        //composition_r1_c2_W shape = (128, 128, 3, 3)
        layerData["composition_r1_c2_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r1_c2_b")
        //composition_r1_c2_b shape = (128,)
        layerData["composition_r1_c1_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r1_c1_W")
        //composition_r1_c1_W shape = (128, 128, 3, 3)
        layerData["composition_r1_c1_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r1_c1_b")
        //composition_r1_c1_b shape = (128,)
        layerData["composition_r1_b1_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r1_b1_gamma")
        //composition_r1_b1_gamma shape = (128,)
        layerData["composition_r1_b1_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r1_b1_beta")
        //composition_r1_b1_beta shape = (128,)
        layerData["composition_r1_b2_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r1_b2_gamma")
        //composition_r1_b2_gamma shape = (128,)
        layerData["composition_r1_b2_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r1_b2_beta")
        //composition_r1_b2_beta shape = (128,)
        layerData["composition_r2_c2_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r2_c2_W")
        //composition_r2_c2_W shape = (128, 128, 3, 3)
        layerData["composition_r2_c2_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r2_c2_b")
        //composition_r2_c2_b shape = (128,)
        layerData["composition_r2_c1_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r2_c1_W")
        //composition_r2_c1_W shape = (128, 128, 3, 3)
        layerData["composition_r2_c1_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r2_c1_b")
        //composition_r2_c1_b shape = (128,)
        layerData["composition_r2_b1_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r2_b1_gamma")
        //composition_r2_b1_gamma shape = (128,)
        layerData["composition_r2_b1_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r2_b1_beta")
        //composition_r2_b1_beta shape = (128,)
        layerData["composition_r2_b2_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r2_b2_gamma")
        //composition_r2_b2_gamma shape = (128,)
        layerData["composition_r2_b2_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r2_b2_beta")
        //composition_r2_b2_beta shape = (128,)
        layerData["composition_r3_c2_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r3_c2_W")
        //composition_r3_c2_W shape = (128, 128, 3, 3)
        layerData["composition_r3_c2_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r3_c2_b")
        //composition_r3_c2_b shape = (128,)
        layerData["composition_r3_c1_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_r3_c1_W")
        //composition_r3_c1_W shape = (128, 128, 3, 3)
        layerData["composition_r3_c1_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_r3_c1_b")
        //composition_r3_c1_b shape = (128,)
        layerData["composition_r3_b1_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r3_b1_gamma")
        //composition_r3_b1_gamma shape = (128,)
        layerData["composition_r3_b1_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r3_b1_beta")
        //composition_r3_b1_beta shape = (128,)
        layerData["composition_r3_b2_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_r3_b2_gamma")
        //composition_r3_b2_gamma shape = (128,)
        layerData["composition_r3_b2_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_r3_b2_beta")
        //composition_r3_b2_beta shape = (128,)
        layerData["composition_b4_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_b4_gamma")
        //composition_b4_gamma shape = (64,)
        layerData["composition_b4_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_b4_beta")
        //composition_b4_beta shape = (64,)
        layerData["composition_b5_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_b5_gamma")
        //composition_b5_gamma shape = (32,)
        layerData["composition_b5_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_b5_beta")
        //composition_b5_beta shape = (32,)
        layerData["composition_b1_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_b1_gamma")
        //composition_b1_gamma shape = (32,)
        layerData["composition_b1_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_b1_beta")
        //composition_b1_beta shape = (32,)
        layerData["composition_b2_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_b2_gamma")
        //composition_b2_gamma shape = (64,)
        layerData["composition_b2_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_b2_beta")
        //composition_b2_beta shape = (64,)
        layerData["composition_b3_gamma"] = StyleModelData(modelName: "composition",rawFileName: "composition_b3_gamma")
        //composition_b3_gamma shape = (128,)
        layerData["composition_b3_beta"] = StyleModelData(modelName: "composition",rawFileName: "composition_b3_beta")
        //composition_b3_beta shape = (128,)
        layerData["composition_c3_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_c3_W")
        //composition_c3_W shape = (128, 64, 4, 4)
        layerData["composition_c3_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_c3_b")
        //composition_c3_b shape = (128,)
        layerData["composition_c2_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_c2_W")
        //composition_c2_W shape = (64, 32, 4, 4)
        layerData["composition_c2_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_c2_b")
        //composition_c2_b shape = (64,)
        layerData["composition_c1_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_c1_W")
        //composition_c1_W shape = (32, 3, 9, 9)
        layerData["composition_c1_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_c1_b")
        //composition_c1_b shape = (32,)
        layerData["composition_d2_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_d2_W")
        //composition_d2_W shape = (64, 32, 4, 4)
        layerData["composition_d2_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_d2_b")
        //composition_d2_b shape = (32,)
        layerData["composition_d3_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_d3_W")
        //composition_d3_W shape = (32, 3, 9, 9)
        layerData["composition_d3_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_d3_b")
        //composition_d3_b shape = (3,)
        layerData["composition_d1_W"] = StyleModelData(modelName: "composition",rawFileName: "composition_d1_W")
        //composition_d1_W shape = (128, 64, 4, 4)
        layerData["composition_d1_b"] = StyleModelData(modelName: "composition",rawFileName: "composition_d1_b")
        //composition_d1_b shape = (64,)    
    }
}
